// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reactivities.Persistence;

#nullable disable

namespace Reactivities.Persistence.Migrations
{
    [DbContext(typeof(ReactivitiesContext))]
    partial class ReactivitiesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reactivities.Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a410364f-6c61-41e7-943e-523047e50036"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 7, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4065),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("9b368a89-f5da-4818-8fe8-85be50720a03"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2023, 8, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4081),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("81878cbd-22d4-427e-aaea-deee106811c9"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2023, 10, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4083),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("81b377b6-eee8-43c0-b233-7987a95180e1"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 11, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("5d01e52c-234e-483e-8078-8353dc7845b5"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 12, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4109),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("5ae4508b-f327-4f4b-9c99-429dc42e5d3f"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 1, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4112),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("46accda4-a920-4485-9c1f-cadddfdee6d3"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 2, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4115),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("8ad26443-ed57-4956-b980-edac70b7cb3b"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 3, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4118),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("1710f0d1-f873-4364-88b7-b4a3e96bc716"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 4, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4120),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("95a23bcd-ca37-48be-968b-96da9e92e219"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 5, 25, 15, 44, 17, 901, DateTimeKind.Utc).AddTicks(4123),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
