version: "3.3"

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Monkeydluffy@123"
    ports:
      - 1433:1433
    volumes:
      - my-volume-mssql:/var/opt/mssql
  postgres_blog:
    container_name: postgres_blog
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Monkeydluffy@123
      - PGDATA= /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  postgres:
    driver: bridge
volumes:
  my-volume-mssql:
  postgres:
