version: "3.3"

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Monkeydluffy@123"
    ports:
      - 1433:1433
    volumes:
      - my-volume-mssql:/var/opt/mssql

volumes:
  my-volume-mssql:
