version: "3.3"

services:
  sql-server-db:
    container_name: mssql-reactivities
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - mssqldata:/var/opt/mssql 
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Monkeydluffy@123"
      ACCEPT_EULA: "Y"
volumes:
  mssqldata:
